name: "Enecle エネクル"
description: "Unofficial add-on for Enecle (エネクル) gas monitoring service."
version: "1.0.0"
slug: "enecle"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8123  