# .github/workflows/build.yml
name: Go Cross Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64, arm]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build for Linux ${{ matrix.arch }}
        run: |
          mkdir -p build
          case "${{ matrix.arch }}" in
            amd64)
              GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/enecle-linux-amd64 .
              ;;
            arm64)
              GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o build/enecle-linux-arm64 .
              ;;
            arm)
              GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o build/enecle-linux-arm .
              ;;
          esac

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: enecle-${{ matrix.arch }}
          path: build/enecle-*
